name: Build and Package fox-convert

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish self-contained linux-x64
      run: dotnet publish -c Release -r linux-x64 --self-contained true -o publish-linux/

    - name: Prepare .deb package structure
      run: |
        if [ "$GITHUB_REF_TYPE" = "tag" ]; then
        VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')
        else
          VERSION="0.0.0-dev"
        fi
        mkdir -p fox-convert_${VERSION}/DEBIAN
        mkdir -p fox-convert_${VERSION}/usr/local/bin
        cp -r publish-linux/* fox-convert_${VERSION}/usr/local/bin/
        echo "Package: fox-convert
        Version: $VERSION
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Halkion <halkion@yahoo.com>
        Description: CLI tool to convert Chrome extensions to Firefox extensions." > fox-convert_${VERSION}/DEBIAN/control

    - name: Build .deb package
      run: |
        VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
        dpkg-deb --build fox-convert_${VERSION}

    - name: Upload .deb as artifact
      uses: actions/upload-artifact@v4
      with:
        name: fox-convert-deb
        path: fox-convert_*.deb

    - name: Upload .deb to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: fox-convert_*.deb
